
// INITIAL VALUES
export const INITIAL_BASE_CURRENCY = 'USD'

// ACTIONS TYPE
export const SET_ALL_RATES = 'SET_ALL_RATES';
export const SET_ACTIVE_CURRENCY = 'SET_ACTIVE_CURRENCY';
export const SET_EXCHANGE_CURRENCY = 'SET_EXCHANGE_CURRENCY';
export const SET_ACTIVE_INPUT_ID = 'SET_ACTIVE_INPUT_ID';
export const SET_ACTIVE_INPUT_VALUE = 'SET_ACTIVE_INPUT_VALUE';
export const SET_RATIO = 'SET_RATIO';
export const ADD_SELECTS_VALUE = 'ADD_SELECTS_VALUE';
export const SET_AUTH_TYPE = 'SET_AUTH_TYPE';
export const ADD_ACTIVE_RATE = 'ADD_ACTIVE_RATE';
export const REMOVE_ACTIVE_RATE = 'REMOVE_ACTIVE_RATE';
export const SET_INITIAL_RATES = 'SET_INITIAL_RATES';
export const SET_ALL_RATES_AS_ACTIVE = 'SET_ALL_RATES_AS_ACTIVE'

//ROUTES
export const MAIN_PAGE_ROUTE = '/';
export const LOGIN_ROUTE = '/login';
export const AUTH_ROUTE = '/auth'
export const ERROR_ROUTE = '/error';