
// INITIAL VALUES
export const INITIAL_BASE_CURRENCY = 'USD'

// ACTIONS TYPE
export const SET_ALL_RATES = 'SET_ALL_RATES'
export const SET_ACTIVE_CURRENCY = 'SET_ACTIVE_CURRENCY';
export const SET_EXCHANGE_CURRENCY = 'SET_EXCHANGE_CURRENCY';
export const SET_ACTIVE_INPUT_ID = 'SET_ACTIVE_INPUT_ID';
export const SET_ACTIVE_INPUT_VALUE = 'SET_ACTIVE_INPUT_VALUE';
export const SET_RATIO = 'SET_RATIO';
export const ADD_SELECTS_VALUE = 'ADD_SELECTS_VALUE'

